# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/oriole/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oriole)

$(call add-radio-file-sha1-checked,radio/abl.img,47b28b9e4d803866fd88f66c5ab252138cc379c1)
$(call add-radio-file-sha1-checked,radio/bl1.img,43525580b342ec41aa7d7275c9345bb5e992528b)
$(call add-radio-file-sha1-checked,radio/bl2.img,a533d13487cd944eef7cccffdf8151c6f4ab2937)
$(call add-radio-file-sha1-checked,radio/bl31.img,5242e5cbed83a0f8712454cd44e0804aa5340123)
$(call add-radio-file-sha1-checked,radio/gsa.img,d83652808e364acafabd428c67b95d9f76f7cf25)
$(call add-radio-file-sha1-checked,radio/ldfw.img,2e9b9b0c234dcb781c99cac113dd5773d8fc62f0)
$(call add-radio-file-sha1-checked,radio/modem.img,8e79b671b9758580b0862e0a3607f183e0959ac5)
$(call add-radio-file-sha1-checked,radio/pbl.img,af9b31c44e2589299021530be46e517c6ff7451d)
$(call add-radio-file-sha1-checked,radio/tzsw.img,da786e717763e9fda3724597ee15efc7ae030611)

endif
